name: bun_test
on: [pull_request, push]

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
