name: bun_build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_build:
    name: run_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
